# Learn more at https://github.com/carlosperate/awesome-pyproject
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# https://github.com/hhatto/autopep8/blob/master/README.rst#pyproject-toml
[tool.autopep8]
max_line_length = 88
in-place = true
recursive = true
jobs = 0

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 88
target-version = ['py37', 'py38']

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/options
py_version = 37
color_output = true
profile = "black"


[tool.pytest.ini_options]
minversion = "6.0"

[tool.towncrier]

[tool.darker]
revision = "main"
diff = true
check = true
isort = true
lint = [
    "pylint",
    "mypy",
    "flake8"
]
log_level = "INFO"

