# Learn more at <https://github.com/carlosperate/awesome-pyproject>
# Cool info <https://blog.pilosus.org/posts/2019/12/26/python-third-party-tools-configuration/>
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# https://github.com/hhatto/autopep8/blob/master/README.rst#pyproject-toml
[tool.autopep8]
max_line_length = 88
in-place = true
recursive = true
jobs = 0

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
#line-length = 88
target-version = ['py37', 'py38', 'py39']
color = true
safe = true

#
[tool.interrogate]
color = true
generate_badge = "."
verbose = 2

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/options
py_version = 37
color_output = true
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"

[tool.towncrier]

[tool.darker]
revision = "main"
diff = true
check = true
isort = true
lint = ["pylint", "mypy", "flake8"]
log_level = "INFO"

# disable = "R0801"
[tool.pylint.MASTER]
jobs = 0

[tool.pylint."MESSAGES CONTROL"]
disable = "duplicate-code"
