# Learn more at <https://github.com/carlosperate/awesome-pyproject>
# Cool info <https://blog.pilosus.org/posts/2019/12/26/python-third-party-tools-configuration/>
#https://setuptools.readthedocs.io/en/latest/build_meta.html
#https://peps.python.org/pep-0621/
[project]
name = "valuefragments"
version = "0.1.22"
description = "Testing installation of Package"
authors = [{ name = "Ebeling, Dr. Bastian", email = "bastian.ebeling@web.de" }]
requires-python = ">=3.11,<4.0"

[project.optional-dependencies]
allfeatures = ["psutil", "hashlib", "icecream", "cpu_load_generator"]

[tool.poetry]
name = "valuefragments"
version = "0.1.22"
description = "Testing installation of Package"
authors = ["Ebeling, Dr. Bastian <bastian.ebeling@web.de>"]

[tool.poetry.group.dev.dependencies]
joblib = "^1.2.0"
bandit = "^1.7.4"
pylama = { extras = ["all"], version = "^8.4.1" }

[build-system]
#https://www.python.org/dev/peps/pep-0508/
#https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
requires = ["setuptools>=65.5.1", "wheel>=0.38.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]

# ...
# By default, include-package-data is true in pyproject.toml, so you do
# NOT have to specify this line.
#include_package_data = true
#packages = "find:"
#package_dir = "src"
#### explicitly not coverred
#[tool.poetry.extras]
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
#mypkg = ["*.txt", "*.rst"]
"*" = ["py.typed"]

# https://github.com/hhatto/autopep8/blob/master/README.rst#pyproject-toml
[tool.autopep8]
max_line_length = 79
in-place = true
recursive = true
jobs = 0

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 79
target-version = ['py311'] #'py37', 'py38',
color = true
safe = true

#force-exlude = ".*/venv/.*"
[tool.darker]
revision = "main"
diff = true
check = true
isort = true
lint = ["pylint", "mypy", "flake8"]
log_level = "INFO"

[tool.ufmt]

[tool.pylint.format]
max-line-length = "88"

#[tool.flake8]
#max-line-length = 88
#extend-ignore = "E203"
# https://interrogate.readthedocs.io/en/latest/#configuration
[tool.interrogate]
color = true
generate_badge = "."
verbose = 2

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
enable_incomplete_feature = "Unpack"
pretty = true
show_error_codes = true
show_error_context = true
strict = true

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/options
#extend_skip = ["venv"]
py_version = 311
color_output = true
profile = 'black'

[tool.poetry.dependencies]
python = "^3.11"
typing-extensions = "*"

[tool.poetry.dependencies.joblib]
version = "*"
optional = true

[tool.poetry.dependencies.cpu-load-generator]
version = "*"
optional = true

[tool.poetry.dependencies.hashlib]
version = "*"
optional = true

[tool.poetry.dependencies.icecream]
version = "*"
optional = true

[tool.poetry.dependencies.psutil]
version = "*"
optional = true

[tool.poetry.dev-dependencies]
autopep8 = "*"
black = "*"
build = "*"
cpu-load-generator = "*"
flake8 = "*"
icecream = "*"
mccabe = "*"
mypy = "*"
pep257 = "*"
pep8 = "*"
pycodestyle = "*"
pydocstyle = "*"
pyflakes = "*"
pyleft = "*"
pylint = "*"
pyre-check = "*"
pyright = "*"
pytest = "*"
radon = "*"
setuptools = ">=65.5.1"
toml = "*"
ufmt = "*"
vermin = "*"
yapf = "*"

[tool.poetry.dev-dependencies.isort]
version = "*"
extras = ["colors"]

[tool.poetry.dev-dependencies.prospector]
version = "*"
extras = ["with_everything"]

[tool.poetry.dev-dependencies.pylama]
version = "*"
extras = ["all"]

[tool.poetry.dev-dependencies.pytype]
version = ">=2022.09.27"
python = "~3.10"

#[pylama.pep8]
#max_line_length = 79
[tool.pylint.main]
jobs = 0
py-version = "3.11"
output-format = "colorized"

[tool.pylint.basic]
include-naming-hint = "y"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false

[tool.pylama]
linters = [""] # means all
#linters = ["mypy,pycodestyle,pydocstyle,pyflakes,pylint,isort"]
verbose = true
concurrent = true
max_line_length = 79

[tool.pylint."MESSAGES CONTROL"]
disable = "duplicate-code"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = ["--verbose"]

[tool.towncrier]

#https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
[[tool.mypy.overrides]]
module = ["psutil", "icecream", "cpu_load_generator"]
ignore_missing_imports = true
