# Learn more at <https://github.com/carlosperate/awesome-pyproject>
# Cool info <https://blog.pilosus.org/posts/2019/12/26/python-third-party-tools-configuration/>
#https://setuptools.readthedocs.io/en/latest/build_meta.html
[build-system]
#https://www.python.org/dev/peps/pep-0508/
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# https://github.com/hhatto/autopep8/blob/master/README.rst#pyproject-toml
[tool.autopep8]
max_line_length = 88
in-place = true
recursive = true
jobs = 0

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
#line-length = 88
target-version = ['py39'] #'py37', 'py38',
color = true
safe = true
#force-exlude = ".*/venv/.*"

[tool.darker]
revision = "main"
diff = true
check = true
isort = true
lint = ["pylint", "mypy", "flake8"]
log_level = "INFO"

[tool.flake8]
max-line-length = 88

# https://interrogate.readthedocs.io/en/latest/#configuration
[tool.interrogate]
color = true
generate_badge = "."
verbose = 2

[tool.mypy]
strict = true
show_error_codes = true
show_error_context = true

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/options
py_version = 39
color_output = true
profile = "black"
skip = "venv"

[tool.poetry]
name = "valuefragments"
version = "0.1.1"
description = "Testing installation of Package"
authors = ["Ebeling, Dr. Bastian <bastian.ebeling@web.de>"]

[tool.poetry.dependencies]
python = ">=3.9"
cpu-load-generator = {version = "*", optional = true}
hashlib = {version = "*", optional = true}
icecream = {version = "*", optional = true}
psutil = {version = "*", optional = true}
typing-extensions = "*"

[tool.poetry.dev-dependencies]
pylama = "*"
pyre-check = "*"
pydocstyle = "*"
isort = "*"
black = "*"
pylint = "*"
pyright = "*"
mypy = "*"
radon = "*"
pyflakes = "*"
pycodestyle = "*"
pep257 = "*"
pep8 = "*"
mccabe = "*"
pytest = "*"
[pylama.pep8]
max_line_length = 88

[tool.pylint.MASTER]
jobs = 0
output-format = "colorized"
include-naming-hint = "y"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false

[tool.pylint."MESSAGES CONTROL"]
disable = "duplicate-code"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = ["--verbose"]

[tool.towncrier]
