python3 -OO -m timeit "from importlib.util import find_spec; find_spec(""typing"")"
python3 -OO -m timeit --process "from importlib.util import find_spec; find_spec(""typing"")"
python3 -OO -m timeit "getattr(__import__(""importlib.util"",fromlist=[""util""]),""find_spec"")(""typing"")"
python3 -OO -m timeit --process "getattr(__import__(""importlib.util"",fromlist=[""util""]),""find_spec"")(""typing"")"
python3 -OO -m timeit "__import__(""importlib.util"",fromlist=[""util""]).find_spec(""typing"")"
python3 -OO -m timeit --process "__import__(""importlib.util"",fromlist=[""util""]).find_spec(""typing"")"
echo "====================================================================== importtime ======================================================================"
python3 -OO -X importtime -c "from importlib.util import find_spec; find_spec(""typing"")" 
python3 -OO -X importtime -c "getattr(__import__(""importlib.util"",fromlist=[""util""]),""find_spec"")(""typing"")" 
python3 -OO -X importtime -c "__import__(""importlib.util"",fromlist=[""util""]).find_spec(""typing"")" 
